name: midoss_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=>3.8
  - numpy
  - pandas
  - geopandas
  - yaml
  - xarray
  - netcdf4
  - pip
  - jupyterlab
  - matplotlib
  - cmocean
  - Cartopy
  - pip:
      - h5py
