name: midoss_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=>3.8
  - numpy
  - pandas
  - matplotlib
  - yaml
  - geopandas
  - xarray
  - netcdf4
  - pip
  - jupyterlab
  - cmocean
  - pip:
      - h5py
